name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Redudant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
           access_token: ${{ github.token }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 14.21.3
      - name: install Dependencies demo 
        run: npm install --no-audit --no-fund --no-optional
      - name: Build
        run: npm run build
      - name: Test Unit
        run: npm run test
      - name: lint
        run: npm run eslint

