name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 14.21.3
      - name: install Dependencies demo 
        run: npm install
      - name: Test Unit
        run: npm run test
      - name: lint
        run: npm run eslint

